-- OBSIDIAN CONFLICT OFFICIAL MAP
--[[
	PASTE TEXT HERE

]]
MAP_BREIFING = [[Obsidian Conflict

Map: oc_stitches_2
Author: Tysn

Description:

The search for the lieutenant continues...


]]
MAP_CONFIG = {
	oc_stitches_2
{
	"mp_falldamage"	"1"
	"sk_max_357" "24"
	"sk_max_ar2" "120"
	"sk_max_buckshot" "60"
        "sk_max_crossbow" "20"
	"sk_max_pistol" "300"
	"sk_max_rpg_round" "9"
        "sk_max_smg1" "500"
	"mp_flashlight" "1"
	"mp_playercollide" "1"
    Remove
    {
        Origin
        {
            "10530 4699.85 -960.093" {}
            "10738 4702 -960.093" {}
        }
    }
    Add
    {
        "item_box_alyxrounds"
        {
            "angles" "0 180 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "hammerid" "118952"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "3989 772 -863.72"
        }
        "item_box_alyxrounds"
        {
            "angles" "0 180 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "hammerid" "118956"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "3989 733 -863.72"
        }
        "weapon_scripted"
        {
            "angles" "0 60 -90"
            "customweaponscript" "custom_spas12"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "3200 1152 -564"
        }
        "item_box_buckshot"
        {
            "angles" "0 201.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "3190 1173 -575.799"
        }
        "item_box_buckshot"
        {
            "angles" "0 107.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "3206 1118 -575.799"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/cafeteria_table001a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6745 2024 -112.465"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/cafeteria_table001a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6614 2025 -112.465"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/cafeteria_table001a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6745 1818 -112.465"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/cafeteria_table001a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6614 1819 -112.465"
        }
        "weapon_smg1"
        {
            "angles" "0 337.5 90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6788 1825 -96"
        }
        "weapon_357"
        {
            "angles" "0 212 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6729 1819 -93"
        }
        "weapon_shotgun"
        {
            "angles" "0 149.5 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6642 1827 -94"
        }
        "weapon_stunstick"
        {
            "angles" "0 43 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6596 1821 -93"
        }
        "weapon_stunstick"
        {
            "angles" "0 44.5 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6584 1822 -93"
        }
        "weapon_stunstick"
        {
            "angles" "0 46.5 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6572 1823 -93"
        }
        "weapon_scripted"
        {
            "angles" "-0.83764 351.248 -96.1446"
            "customweaponscript" "custom_oicw"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6633 2018 -88.4864"
        }
        "weapon_crossbow"
        {
            "angles" "0 338.5 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6578 2029 -94"
        }
        "weapon_ar2"
        {
            "angles" "0 15 118"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6707 2030 -90"
        }
        "item_ammo_smg1"
        {
            "angles" "0 0 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6625 2033 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 354.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6642 2033 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 0 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6658 2033 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 300.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6796 1811 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 270 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6774 1806 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 181.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6756 1811 -96.6126"
        }
        "item_ammo_smg1"
        {
            "angles" "0 224 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6769 1824 -96.6126"
        }
        "item_ammo_357"
        {
            "angles" "0 76 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6705 1815 -96.6816"
        }
        "item_ammo_357"
        {
            "angles" "0 98 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6718 1825 -96.6816"
        }
        "item_box_buckshot"
        {
            "angles" "0 116.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6662 1811 -96.6635"
        }
        "item_box_buckshot"
        {
            "angles" "0 66 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6638 1813 -96.6635"
        }
        "item_ammo_crossbow"
        {
            "angles" "0 123.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6576 2021 -95.4761"
        }
        "item_ammo_crossbow"
        {
            "angles" "0 289 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6567 2021 -95.4761"
        }
        "item_ammo_ar2"
        {
            "angles" "0 25.5 -90"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6699 2016 -94"
        }
        "item_ammo_ar2"
        {
            "angles" "0 45 -90"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6712 2017 -94"
        }
        "item_ammo_ar2"
        {
            "angles" "0 63.5 -90"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6724 2021 -94"
        }
        "item_battery"
        {
            "angles" "0 256 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6761 2032 -96.6809"
        }
        "item_battery"
        {
            "angles" "0 262.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6775 2035 -96.6809"
        }
        "item_battery"
        {
            "angles" "0 33 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6786 2030 -96.6809"
        }
        "item_healthkit"
        {
            "angles" "0 335 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6754 2020 -96.6767"
        }
        "item_healthkit"
        {
            "angles" "0 247 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6781 2022 -96.6767"
        }
        "item_item_crate"
        {
            "angles" "0 277 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_uzi"
            "ItemCount" "1"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6651 1831 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 0 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_ammo_smg1"
            "ItemCount" "3"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6604 1828 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 277 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_shotgun"
            "ItemCount" "1"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6615 2016 -127"
        }
        "item_item_crate"
        {
            "angles" "0 281 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_alyxgun"
            "ItemCount" "1"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6825 1812 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 180.5 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_box_alyxrounds"
            "ItemCount" "5"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6862 1810 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 277 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_frag"
            "ItemCount" "3"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6665 1919 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 347 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_frag"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "6703 1935 -127.812"
        }
        "item_item_crate"
        {
            "angles" "0 24.5 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "weapon_slam"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741824"
            "origin" "6682 1926 -103.249"
        }
        "weapon_slam"
        {
            "angles" "0 27.5 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6716.53 1895.05 -122.812"
        }
        "weapon_slam"
        {
            "angles" "0 296 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6727 1906 -122.812"
        }
        "item_ammo_pistol"
        {
            "angles" "0 163 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6702.48 1903.39 -127.813"
        }
        "item_ammo_pistol"
        {
            "angles" "0 163 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6690.64 1903.52 -127.813"
        }
        "item_ammo_pistol"
        {
            "angles" "0 97 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6672 1895 -127.813"
        }
        "item_ammo_pistol"
        {
            "angles" "0 28 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6730 1945 -127.813"
        }
        "item_ammo_pistol"
        {
            "angles" "0 309 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6721 1958 -127.813"
        }
        "prop_dynamic_override"
        {
            "angles" "0 180 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/interior_fence003d.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6915.04 2018 -67.654"
        }
        "prop_dynamic_override"
        {
            "angles" "0 150 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/interior_fence003d.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6900 1956 -67.654"
        }
        "prop_dynamic_override"
        {
            "angles" "0 180 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/interior_fence003d.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6884 1894 -67.654"
        }
        "prop_dynamic_override"
        {
            "angles" "0 180 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_wasteland/interior_fence003d.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6884 1825 -67.654"
        }
        "prop_dynamic_override"
        {
            "angles" "0 90 90"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_debris/metal_panel01a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6752 1757 -65"
        }
        "prop_dynamic_override"
        {
            "angles" "0 90 90"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_debris/metal_panel01a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6560 1757 -65"
        }
        "npc_turret_floor"
        {
            "angles" "0 49.5 0"
            "model" "models/combine_turrets/floor_turret.mdl"
            "SkinNumber" "0"
            "spawnflags" "0"
            "teamnumber" "0"
            "origin" "6385 1652 -128.093"
        }
        "weapon_frag"
        {
            "angles" "0 317.5 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741823"
            "origin" "6932 2027 -126"
        }
        "prop_physics"
        {
            "angles" "0 0 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "256"
            "origin" "6805.7 1729.2 -127.812"
        }
        "prop_physics"
        {
            "angles" "0 0 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "1"
            "spawnflags" "256"
            "origin" "6967.51 1651.32 -127.812"
        }
        "prop_physics"
        {
            "angles" "0 26 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "2"
            "spawnflags" "257"
            "origin" "6676 1645 -113.593"
        }
        "prop_physics"
        {
            "angles" "0 282 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6622 1699 -109.521"
        }
        "prop_physics"
        {
            "angles" "0 275 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6622 1659 -103.86"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 90"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_debris/metal_panel01a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6325 1635 -68"
        }
        "prop_dynamic_override"
        {
            "angles" "0 270 90"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "health" "0"
            "MaxAnimTime" "10"
            "maxdxlevel" "0"
            "MinAnimTime" "5"
            "mindxlevel" "0"
            "model" "models/props_debris/metal_panel01a.mdl"
            "PerformanceMode" "0"
            "pressuredelay" "0"
            "RandomAnimation" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "SetBodyGroup" "0"
            "skin" "0"
            "solid" "6"
            "spawnflags" "0"
            "origin" "6445 1635 -68"
        }
        "weapon_frag"
        {
            "angles" "0 203 -90"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741823"
            "origin" "6924 2022 -126.928"
        }
        "prop_physics"
        {
            "angles" "0 0 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6901 1899 -127.812"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_ar2"
            "angles" "0 278 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "7406.51 2907.01 -832.093"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_ar2"
            "angles" "0 255 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "7536.53 2912.33 -707.658"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_ar2"
            "angles" "0 345 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "6547.55 2722.8 -960.093"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_ar2"
            "angles" "0 196 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "7978.9 2782.42 -960.093"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_ar2"
            "angles" "0 290 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "6925 2904 -707.52"
        }
        "npc_combine_s"
        {
            "additionalequipment" "weapon_smg1"
            "angles" "0 252 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "followonspawn" "0"
            "hintlimiting" "0"
            "ignoreunseenenemies" "0"
            "model" "models/combine_soldier.mdl"
            "npchealth" "0"
            "NumGrenades" "0"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "sleepstate" "0"
            "spawnflags" "401409"
            "squadname" "combine"
            "tacticalvariant" "0"
            "teamnumber" "0"
            "usemarch" "0"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "7533 2910 -832.093"
        }
        "npc_turret_floor"
        {
            "angles" "0 298.5 0"
            "model" "models/combine_turrets/floor_turret.mdl"
            "SkinNumber" "0"
            "spawnflags" "0"
            "teamnumber" "0"
            "origin" "7076 2849 -960.093"
        }
        "npc_turret_floor"
        {
            "angles" "0 223 0"
            "model" "models/combine_turrets/floor_turret.mdl"
            "SkinNumber" "0"
            "spawnflags" "0"
            "teamnumber" "0"
            "origin" "7596.55 2851.28 -960.093"
        }
        "prop_physics"
        {
            "angles" "0 230 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "hammerid" "104120"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001_explosive.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "257"
            "OnBreak" "Zone2_Maker_ExplosiveBarrel,ForceSpawn,,0,-1"
            "origin" "7022 2825 -959.812"
        }
        "weapon_scripted"
        {
            "angles" "0 240 -90"
            "customweaponscript" "custom_spas12"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "8518 4494 -923"
        }
        "item_box_buckshot"
        {
            "angles" "0 197 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "8509.39 4510.05 -926"
        }
        "item_box_buckshot"
        {
            "angles" "0 197 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "8507.39 4657.05 -922.849"
        }
        "weapon_shotgun"
        {
            "angles" "0 254 -90"
            "customweaponscript" "custom_spas12"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "8512 4640 -922"
        }
        "npc_combine_s"
        {
            "additionalequipment" "custom_g36c"
            "angles" "0 273.5 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "hammerid" "94699"
            "hintlimiting" "0"
            "model" "models/combine_elite_soldier.mdl"
            "npchealth" "225"
            "npcname" "Lieutenant's Guard"
            "NumGrenades" "999999"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "skin" "0"
            "sleepstate" "0"
            "spawnflags" "401671"
            "squadname" "Guards"
            "tacticalvariant" "1"
            "targetname" "Lieutenant_Guard"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "10625 4731 -956"
        }
        "weapon_scripted"
        {
            "angles" "0 177.5 -90"
            "customweaponscript" "custom_oicw"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6945 4460 -919.849"
        }
        "item_ammo_smg1"
        {
            "angles" "0 113 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6971.53 4447.24 -925.644"
        }
        "item_ammo_smg1"
        {
            "angles" "0 94.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6948 4444 -925.644"
        }
        "item_ammo_smg1"
        {
            "angles" "0 79.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6924 4444 -925.644"
        }
        "item_ammo_smg1"
        {
            "angles" "0 79.5 0"
            "disableshadows" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "6900 4444 -925.644"
        }
        "item_item_crate"
        {
            "angles" "0 346 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_ammo_smg1"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "7124.37 4456.18 -925.707"
        }
        "item_item_crate"
        {
            "angles" "0 3.00001 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_ammo_smg1"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "7175 4456 -925.707"
        }
        "item_item_crate"
        {
            "angles" "0 297.5 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_ammo_smg1"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "7150 4466 -959.812"
        }
        "item_item_crate"
        {
            "angles" "0 240.5 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_battery"
            "ItemCount" "2"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "7221 4665 -959.812"
        }
        "item_suitcharger"
        {
            "angles" "0 270 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "spawnflags" "0"
            "origin" "7177 4689 -907"
        }
        "item_healthcharger"
        {
            "angles" "0 270 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "origin" "7146 4688 -907"
        }
        "npc_combine_s"
        {
            "additionalequipment" "custom_g36c"
            "angles" "0 273.5 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "hammerid" "94699"
            "hintlimiting" "0"
            "model" "models/combine_elite_soldier.mdl"
            "npchealth" "225"
            "npcname" "Lieutenant's Guard"
            "NumGrenades" "999999"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "skin" "0"
            "sleepstate" "0"
            "spawnflags" "401671"
            "squadname" "Guards"
            "tacticalvariant" "1"
            "targetname" "Lieutenant_Guard"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "10522.5 4696.62 -957.576"
        }
        "npc_combine_s"
        {
            "additionalequipment" "custom_g36c"
            "angles" "0 273.5 0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "hammerid" "94699"
            "hintlimiting" "0"
            "model" "models/combine_elite_soldier.mdl"
            "npchealth" "225"
            "npcname" "Lieutenant's Guard"
            "NumGrenades" "999999"
            "physdamagescale" "1.0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "skin" "0"
            "sleepstate" "0"
            "spawnflags" "401671"
            "squadname" "Guards"
            "tacticalvariant" "1"
            "targetname" "Lieutenant_Guard"
            "waitingtorappel" "No"
            "wakeradius" "0"
            "wakesquad" "0"
            "origin" "10716.9 4700.34 -957.576"
        }
        "prop_physics"
        {
            "angles" "0 0.999998 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6809 1662 -107.931"
        }
        "prop_physics"
        {
            "angles" "0 41 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6780 1704 -107"
        }
        "prop_physics"
        {
            "angles" "0 18 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "256"
            "origin" "6793 1665 -66"
        }
        "prop_physics"
        {
            "angles" "0 348.5 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "256"
            "origin" "6797 1713 -62"
        }
        "prop_physics"
        {
            "angles" "0 225 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6579 1701 -107.931"
        }
        "prop_physics"
        {
            "angles" "0 177.5 -90"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_junk/wood_crate001a.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderdist" "0"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "5"
            "spawnflags" "257"
            "origin" "6543 1660 -107.931"
        }
        "item_item_crate"
        {
            "angles" "0 261.5 0"
            "CrateAppearance" "0"
            "CrateType" "0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "inertiaScale" "1.0"
            "ItemClass" "item_battery"
            "ItemCount" "1"
            "ManageItems" "0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "1073741825"
            "origin" "7361 4455 -925.707"
        }
        "item_ammo_crate"
        {
            "AmmoType" "0"
            "angles" "0 270 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "origin" "7313 4670 -943.812"
        }
        "prop_physics"
        {
            "angles" "0 320.5 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "hammerid" "130671"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "0"
            "spawnflags" "257"
            "origin" "1198 -1319 -255.812"
        }
        "prop_physics"
        {
            "angles" "0 320.5 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "hammerid" "130671"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "1"
            "spawnflags" "257"
            "origin" "1919 -1471 -255.812"
        }
        "prop_physics"
        {
            "angles" "0 320.5 0"
            "damagetoenablemotion" "0"
            "Damagetype" "0"
            "disablereceiveshadows" "0"
            "disableshadows" "0"
            "ExplodeDamage" "0"
            "ExplodeRadius" "0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "forcetoenablemotion" "0"
            "hammerid" "130671"
            "inertiaScale" "1.0"
            "massScale" "0"
            "maxdxlevel" "0"
            "mindxlevel" "0"
            "minhealthdmg" "0"
            "model" "models/props_c17/oildrum001.mdl"
            "nodamageforces" "0"
            "PerformanceMode" "0"
            "physdamagescale" "0.1"
            "pressuredelay" "0"
            "renderamt" "255"
            "rendercolor" "255 255 255"
            "renderfx" "0"
            "rendermode" "0"
            "shadowcastdist" "0"
            "skin" "2"
            "spawnflags" "257"
            "origin" "2060.96 -884.397 -255.812"
        }
        "weapon_slam"
        {
            "angles" "0 331 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "1317 -179 -250.812"
        }
        "weapon_slam"
        {
            "angles" "0 220.5 0"
            "fademaxdist" "0"
            "fademindist" "-1"
            "fadescale" "1"
            "minplayerstospawn" "0"
            "spawnflags" "-1073741824"
            "origin" "1322 -167 -250.812"
        }
    }
    Modify
    {
        ClassName
        {
            "worldspawn"
            {
                "mapversion" "25"
            }
        }
        TargetName
        {
            "Lieutenant"
            {
                "npchealth" "1250"
            }
        }
    }
SpawnItems
{
    "weapon_crowbar" "1"
    "custom_cz52" "1"
    "item_ammo_pistol" "8"
    "weapon_healer" "1"
}
}

}